### ISSUE TITLE
NPE on Android 6.0+

### ISSUE THREAD

**Issue by jaredrummler** [Commit451/ForegroundViews#2]
In Android 6.0+ the foreground drawable is set when the view is instantiated ([see lines 4278-4282](https://github.com/android/platform_frameworks_base/blob/marshmallow-release/core/java/android/view/View.java#L4278-4282)). The [`ForegroundDelegate`](https://github.com/Commit451/ForegroundViews/blob/b686865ada4d7f78f92b56b4b83b11514d1f809d/foregroundviews/src/main/java/com/commit451/foregroundviews/ForegroundDelegate.java) is `null` [here](https://github.com/Commit451/ForegroundViews/blob/master/foregroundviews/src/main/java/com/commit451/foregroundviews/ForegroundRelativeLayout.java#L96), causing a `NullPointerException` to be thrown when the view is inflated.

**Comment by Jawnnypoo** [comment]
Thanks for finding and fixing this! 2.0.3 has the fix

**Comment by jaredrummler** [comment]
Your welcome. A better approach might be to call the super methods on Android 6.0+.

**Comment by Jawnnypoo** [comment]
Thanks for the suggestion, I went ahead and updated 2.1.0 to work this way :smile:
