### ISSUE TITLE
NoSuchMethodError below android 21

### ISSUE THREAD

**Issue by qishi604** [Commit451/ForegroundViews#6]
Use ForegroundRelativeLayout or ForegroundLinearLayout will crash in android 20 and below.I think because of the constructor

```
@TargetApi(Build.VERSION_CODES.LOLLIPOP)
    public ForegroundLinearLayout(Context context, AttributeSet attrs, int defStyleAttr, int defStyleRes) {
        super(context, attrs, defStyleAttr, defStyleRes);

    }
```

**Comment by Jawnnypoo** [comment]
This should have been fixed in version 2.2.0. Can you verify that you are using this version and still seeing this issue?

**Comment by qishi604** [comment]
Sorry! I was used the old version.

**Comment by Jawnnypoo** [comment]
No worries!
